package in.tallybridge.app;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfRenderer;
import android.hardware.biometrics.BiometricManager;
import android.hardware.biometrics.BiometricPrompt;
import android.net.Uri;
import android.os.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.text.NumberFormat;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.Consumer;

/** Native Android Views only. All network and PDF work runs off the UI thread. */
public final class MainActivity extends Activity {
 private static final int NAVY=Color.rgb(16,45,68),TEAL=Color.rgb(23,107,91),MUTED=Color.rgb(89,108,121),BG=Color.rgb(242,246,248);
 private final ExecutorService work=Executors.newSingleThreadExecutor();
 private final Handler main=new Handler(Looper.getMainLooper());
 private CryptoStore store;private BridgeApi api;
 private LinearLayout root,body,header;private ListView list;private TextView titleView,statusView,companyView;private ProgressBar progress;
 private boolean unlocked=false,visible=false,authenticating=false,loginRunning=false,destroyed=false,pollBusy=false;
 private volatile int generation=0;private int loginSerial=0;
 private boolean pdfBusy=false,pairBusy=false;
 private String company="",tab="Home";private JSONObject boot=new JSONObject();
 private final ArrayDeque<Runnable> history=new ArrayDeque<>();private Runnable current;
 private final Map<String,JSONObject> cache=new HashMap<>();private final Map<String,Long> cacheAt=new HashMap<>();
 private boolean forceNext=false;private File savePDF;private CancellationSignal unlockSignal;
 private final NumberFormat currency=NumberFormat.getCurrencyInstance(new Locale("en","IN"));
 private final Runnable poll=new Runnable(){public void run(){if(visible&&unlocked&&!loginRunning&&!pollBusy&&!store.get("device").isEmpty()){pollBusy=true;final int epoch=generation;work.execute(()->{try{JSONObject data=api.get("/api/v1/mobile/status");main.post(()->{if(!destroyed&&unlocked&&epoch==generation){boot=data;updateStatus();if(tab.equals("Home")&&history.isEmpty()&&current!=null)renderHome();}});}catch(Exception e){main.post(()->{if(!destroyed&&unlocked&&epoch==generation){if(e instanceof Http.Failure&&(((Http.Failure)e).status==401||((Http.Failure)e).status==403)){cache.clear();cacheAt.clear();showFailure(e);}else if(statusView!=null)statusView.setText("PC connection unavailable • retrying");}});}finally{main.post(()->pollBusy=false);}});}main.postDelayed(this,15000);}};
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);currency.setCurrency(Currency.getInstance("INR"));try{store=new CryptoStore(this);api=new BridgeApi(store);company=store.get("company");cleanPDFs();}catch(Exception e){fatal(e);return;}main.postDelayed(poll,15000);}
 @Override protected void onResume(){super.onResume();visible=true;if(store==null)return;if(loginRunning){simple("Google sign-in","Choose your Google account to continue.","Cancel sign-in",()->{api.login.cancel();loginSerial++;loginRunning=false;showLock();});return;}if(!unlocked&&!authenticating)showLock();}
 @Override protected void onStop(){super.onStop();visible=false;if(!authenticating){unlocked=false;generation++;cache.clear();cacheAt.clear();} }
 @Override protected void onDestroy(){destroyed=true;generation++;main.removeCallbacksAndMessages(null);if(unlockSignal!=null)unlockSignal.cancel();if(api!=null)api.login.cancel();work.shutdownNow();super.onDestroy();}
 private void fatal(Exception e){TextView v=new TextView(this);v.setPadding(30,60,30,30);v.setText("TallyBridge could not start.\n"+e.getMessage());setContentView(v);}
 private int dp(float x){return Math.round(x*getResources().getDisplayMetrics().density);}
 private TextView text(String value,int size,int color){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(color);v.setPadding(dp(4),dp(5),dp(4),dp(5));return v;}
 private GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 private Button button(String value,Runnable click){Button b=new Button(this);b.setText(value);b.setAllCaps(false);b.setTextColor(TEAL);b.setMinHeight(dp(48));b.setOnClickListener(v->click.run());return b;}
 private void base(String title,boolean navigation){
  root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
  root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});
  header=new LinearLayout(this);header.setOrientation(LinearLayout.VERTICAL);header.setPadding(dp(18),dp(8),dp(18),dp(12));header.setBackgroundColor(NAVY);
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);
  if(navigation&&!history.isEmpty()){Button back=button("‹",this::goBack);back.setTextColor(Color.WHITE);top.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));back.setContentDescription("Back");}
  titleView=text(title,24,Color.WHITE);titleView.setTypeface(null,Typeface.BOLD);top.addView(titleView,new LinearLayout.LayoutParams(0,-2,1));
  if(navigation){Button refresh=button("↻",()->{forceNext=true;if(current!=null)current.run();});refresh.setTextColor(Color.WHITE);refresh.setContentDescription("Refresh current report");top.addView(refresh,new LinearLayout.LayoutParams(dp(48),dp(48)));}
  header.addView(top);root.addView(header);
  if(navigation){companyView=text(company.isEmpty()?"Select company ▾":company+" ▾",15,Color.WHITE);companyView.setMinHeight(dp(44));companyView.setOnClickListener(v->chooseCompany());header.addView(companyView);statusView=text("",12,Color.rgb(178,221,213));header.addView(statusView);updateStatus();}
  progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setIndeterminate(true);progress.setVisibility(View.GONE);root.addView(progress,new LinearLayout.LayoutParams(-1,dp(3)));
  body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
  if(navigation){LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.WHITE);for(String label:new String[]{"Home","Ledgers","Due","Reports","More"}){Button b=button(label,()->rootTab(label));b.setTextSize(11);b.setPadding(0,0,0,0);if(tab.equals(label))b.setTypeface(null,Typeface.BOLD);nav.addView(b,new LinearLayout.LayoutParams(0,dp(56),1));}root.addView(nav);}
  setContentView(root);root.requestApplyInsets();
 }
 private void simple(String title,String message,String action,Runnable click){base(title,false);LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(22),dp(28),dp(22),dp(20));panel.addView(text(message,17,NAVY));panel.addView(button(action,click));body.addView(panel);}
 private void showLock(){generation++;simple("TallyBridge","Your accounts, on your phone.\nUnlock with your phone's fingerprint or screen-lock PIN.","Unlock",this::unlock);}
 private void unlock(){
  KeyguardManager guard=(KeyguardManager)getSystemService(KEYGUARD_SERVICE);
  if(!guard.isDeviceSecure()){new AlertDialog.Builder(this).setTitle("Set a phone screen lock").setMessage("Enable a PIN, password, or pattern in Android settings before using TallyBridge.").setPositiveButton("Open settings",(d,w)->startActivity(new Intent(android.provider.Settings.ACTION_SECURITY_SETTINGS))).setNegativeButton("Cancel",null).show();return;}
  authenticating=true;
  if(Build.VERSION.SDK_INT>=30){unlockSignal=new CancellationSignal();new BiometricPrompt.Builder(this).setTitle("Unlock TallyBridge").setSubtitle("Use your fingerprint or phone screen lock").setAllowedAuthenticators(BiometricManager.Authenticators.BIOMETRIC_STRONG|BiometricManager.Authenticators.DEVICE_CREDENTIAL).build().authenticate(unlockSignal,getMainExecutor(),new BiometricPrompt.AuthenticationCallback(){@Override public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult r){authenticating=false;unlocked=true;begin();}@Override public void onAuthenticationError(int c,CharSequence s){authenticating=false;showLock();toast(s.toString());}});
  }else{Intent intent=guard.createConfirmDeviceCredentialIntent("Unlock TallyBridge","Use your phone screen lock");if(intent==null){authenticating=false;toast("Screen lock unavailable");return;}startActivityForResult(intent,701);}
 }
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==701){authenticating=false;if(result==RESULT_OK){unlocked=true;begin();}else showLock();}else if(request==702&&result==RESULT_OK&&data!=null&&savePDF!=null){Uri target=data.getData();File source=savePDF;work.execute(()->{try(InputStream in=new FileInputStream(source);OutputStream out=getContentResolver().openOutputStream(target)){if(out==null)throw new IOException("Could not open selected file");byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);main.post(()->toast("PDF saved"));}catch(Exception e){main.post(()->toast(e.getMessage()));}});}}
 private void begin(){history.clear();current=null;if(store.get("base").isEmpty()){connectScreen();return;}if(store.get("device").isEmpty()){verifyOwner();return;}base("Connecting",false);int epoch=++generation;progress.setVisibility(View.VISIBLE);work.execute(()->{try{JSONObject s=api.get("/api/v2/native/status");JSONObject b=s.optBoolean("approved")?api.get("/api/v1/mobile/bootstrap"):null;main.post(()->{if(!active(epoch))return;if(b==null){approvalScreen();return;}boot=b;selectInitialCompany();rootTab("Home");});}catch(Exception e){main.post(()->{if(active(epoch))showFailure(e);});}});}
 private boolean active(int epoch){return !destroyed&&unlocked&&generation==epoch;}
 private void connectScreen(){base("Connect your PC",false);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(22),dp(20),dp(22),dp(20));box.addView(text("Enter the subdomain shown in Windows setup → Cloudflare. Sign in using your one allowed Google account.",16,NAVY));EditText url=new EditText(this);url.setSingleLine(true);url.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);url.setHint("https://tally.example.com");url.setText(store.get("base"));box.addView(url);box.addView(button("Sign in with Google",()->startLogin(url.getText().toString())));box.addView(text("Choose your Google account securely on this phone.",13,MUTED));if(!store.get("device").isEmpty())box.addView(button("Back",this::begin));body.addView(box);}
 private void startLogin(String input){final String base;try{base=AccessLogin.baseURL(input);if(!store.get("device").isEmpty()&&!base.equals(store.get("base"))){toast("Reset phone pairing before changing the server address");return;}}catch(Exception e){toast(e.getMessage());return;}
  if(loginRunning)return;loginRunning=true;final int serial=++loginSerial;generation++;simple("Signing in","Opening Google account selection…","Cancel",()->{api.login.cancel();loginSerial++;loginRunning=false;generation++;connectScreen();});work.execute(()->{try{api.login.login(this,base,()->{});main.post(()->{if(destroyed||!loginRunning||serial!=loginSerial)return;loginRunning=false;unlocked=false;if(visible)showLock();});}catch(Exception e){main.post(()->{if(destroyed||!loginRunning||serial!=loginSerial)return;loginRunning=false;unlocked=true;connectScreen();Throwable cause=e.getCause()==null?e:e.getCause();toast("Sign-in failed: "+cause.getMessage());});}});
 }
 private void verifyOwner(){base("Checking allowed account",false);int epoch=++generation;progress.setVisibility(View.VISIBLE);work.execute(()->{try{JSONObject identity=api.identity();store.put("email",identity.getString("email"));main.post(()->{if(active(epoch))pairScreen();});}catch(Exception e){main.post(()->{if(active(epoch))showFailure(e);});}});}
 private void pairScreen(){base("Approve this phone",false);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(22),dp(20),dp(22),dp(20));box.addView(text("Verified Google account: "+store.get("email"),15,TEAL));box.addView(text("On Windows, open Android Phones and generate a pairing code. Enter it here, then approve the matching fingerprint on the PC.",16,NAVY));EditText code=new EditText(this);code.setHint("6-digit desktop code");code.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);code.setFilters(new InputFilter[]{new InputFilter.LengthFilter(6)});box.addView(code);EditText name=new EditText(this);name.setSingleLine(true);name.setHint("Phone name");name.setText(Build.MANUFACTURER+" "+Build.MODEL);box.addView(name);Button pair=button("Request approval",()->{if(pairBusy)return;String c=code.getText().toString().trim();if(!c.matches("[0-9]{6}")){toast("Enter the 6-digit desktop code");return;}pairBusy=true;String phoneName=name.getText().toString();int epoch=++generation;progress.setVisibility(View.VISIBLE);body.setEnabled(false);work.execute(()->{try{if(generation!=epoch){main.post(()->pairBusy=false);return;}api.pair(c,phoneName);main.post(()->{pairBusy=false;if(active(epoch))approvalScreen();});}catch(Exception e){main.post(()->{pairBusy=false;if(active(epoch)){progress.setVisibility(View.GONE);showFailure(e);}});}});});box.addView(pair);box.addView(button("Sign in again",this::connectScreen));box.addView(button("Reset connection",this::reset));body.addView(box);}
 private void approvalScreen(){simple("Waiting for approval","Match this fingerprint with Windows setup → Android Phones:\n\n"+store.get("fingerprint")+"\n\nApproval expires after 10 minutes.","I've approved it — continue",this::begin);body.addView(button("Request a new pairing",()->{store.put("device","");pairScreen();}));}
 private void reset(){new AlertDialog.Builder(this).setTitle("Reset this phone?").setMessage("This clears sign-in and the phone key. You will need to approve it again on the PC. PDFs already exported to other apps remain there.").setPositiveButton("Reset",(d,w)->{try{api.login.cancel();store.reset();cache.clear();cacheAt.clear();history.clear();cleanPDFs();company="";boot=new JSONObject();connectScreen();}catch(Exception e){toast(e.getMessage());}}).setNegativeButton("Cancel",null).show();}
 private void showFailure(Exception e){generation++;String message=e.getMessage()==null?"Could not connect":e.getMessage();simple("Connection needs attention",message,"Retry",this::begin);body.addView(button("Sign in again",this::connectScreen));body.addView(button("Reset this phone",this::reset));}
 private void selectInitialCompany(){JSONArray cs=array(boot,"companies");boolean found=false;for(int i=0;i<cs.length();i++)if(cs.optJSONObject(i)!=null&&company.equals(cs.optJSONObject(i).optString("name")))found=true;if(!found)company=cs.length()>0?cs.optJSONObject(0).optString("name"):"";store.put("company",company);}
 private void chooseCompany(){JSONArray cs=array(boot,"companies");String[] names=new String[cs.length()];for(int i=0;i<cs.length();i++)names[i]=cs.optJSONObject(i).optString("name");if(names.length==0){toast("Open a company in Tally and use Refresh");return;}new AlertDialog.Builder(this).setTitle("Choose company").setItems(names,(d,i)->{company=names[i];store.put("company",company);cache.clear();cacheAt.clear();rootTab("Home");}).show();}
 private void updateStatus(){if(statusView==null)return;JSONObject sync=object(boot,"autoSync");statusView.setText(sync.optBoolean("running")?"Syncing • "+sync.optString("step"):(boot.optBoolean("tallyOnline")?"PC connected • Tally live":"PC connected • saved data"));}
 private void rootTab(String name){history.clear();tab=name;switch(name){case "Home":home();break;case "Ledgers":ledgers(false);break;case "Due":outstanding("receivable");break;case "Reports":reports();break;default:more();}}
 private void open(Runnable next){if(current!=null)history.push(current);next.run();}
 private void goBack(){generation++;if(!history.isEmpty())history.pop().run();else rootTab("Home");}
 @Override public void onBackPressed(){if(unlocked&&!history.isEmpty())goBack();else super.onBackPressed();}
 private static final class Row{String title,detail,amount;Runnable action;boolean heading;Row(String t,String d,String a,Runnable r){title=t;detail=d;amount=a;action=r;}}
 private Row row(String title,String detail,String amount,Runnable action){return new Row(title,detail,amount,action);}
 private Row heading(String title,String detail){Row r=row(title,detail,"",null);r.heading=true;return r;}
 private void rows(String title,List<Row> data,boolean search){base(title,true);if(search){EditText input=new EditText(this);input.setSingleLine(true);input.setHint("Search this list…");input.setTextSize(16);input.setPadding(dp(20),dp(8),dp(20),dp(8));body.addView(input);list=new ListView(this);RowsAdapter adapter=new RowsAdapter(data);list.setAdapter(adapter);input.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){adapter.filter(s.toString());}public void afterTextChanged(Editable e){}});}else{list=new ListView(this);list.setAdapter(new RowsAdapter(data));}list.setDivider(null);list.setClipToPadding(false);list.setPadding(dp(12),dp(8),dp(12),dp(16));body.addView(list,new LinearLayout.LayoutParams(-1,0,1));list.setOnItemClickListener((parent,view,pos,id)->{Row r=(Row)parent.getItemAtPosition(pos);if(r.action!=null)r.action.run();});}
 private final class RowsAdapter extends BaseAdapter {
  final List<Row> all;List<Row> shown;
  RowsAdapter(List<Row> data){all=new ArrayList<>(data);shown=all;}
  void filter(String query){String q=query.trim().toLowerCase(Locale.ROOT);shown=new ArrayList<>();for(Row r:all)if(r.heading||q.isEmpty()||(r.title+" "+r.detail+" "+r.amount).toLowerCase(Locale.ROOT).contains(q))shown.add(r);notifyDataSetChanged();}
  public int getCount(){return shown.size();}public Object getItem(int i){return shown.get(i);}public long getItemId(int i){return i;}
  public View getView(int position,View recycled,android.view.ViewGroup parent){LinearLayout card;if(recycled instanceof LinearLayout)card=(LinearLayout)recycled;else{card=new LinearLayout(MainActivity.this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(16),dp(12),dp(16),dp(12));card.addView(text("",16,NAVY));card.addView(text("",13,MUTED));card.addView(text("",18,TEAL));}Row r=shown.get(position);card.setBackground(shape(r.heading?Color.rgb(224,237,238):Color.WHITE,12));TextView t=(TextView)card.getChildAt(0),d=(TextView)card.getChildAt(1),a=(TextView)card.getChildAt(2);t.setText(r.title+(r.action!=null?"  ›":""));t.setTypeface(null,Typeface.BOLD);d.setText(r.detail);d.setVisibility(r.detail.isEmpty()?View.GONE:View.VISIBLE);a.setText(r.amount);a.setVisibility(r.amount.isEmpty()?View.GONE:View.VISIBLE);card.setContentDescription(r.title+". "+r.detail+" "+r.amount);return card;}
 }
 private void local(String title,Runnable self,List<Row> data,boolean search){generation++;current=self;rows(title,data,search);}
 private void load(String title,String path,Runnable self,Consumer<JSONObject> render){
  current=self;int epoch=++generation;boolean refresh=forceNext;forceNext=false;
  JSONObject saved=cache.get(path);Long when=cacheAt.get(path);if(!refresh&&saved!=null&&when!=null&&System.currentTimeMillis()-when<60000){render.accept(saved);return;}
  rows(title,new ArrayList<>(Arrays.asList(heading("Loading…","Reading safely from the PC"))),false);progress.setVisibility(View.VISIBLE);
  work.execute(()->{try{
   if(generation!=epoch)return;JSONObject value=api.get(path);long deadline=System.currentTimeMillis()+45000;
   while(value.optBoolean("pending")&&System.currentTimeMillis()<deadline){if(generation!=epoch)return;long pause=Math.max(500,Math.min(10000,value.optLong("retryAfterMs",1000)));Thread.sleep(pause);value=api.get(path);}
   if(value.optBoolean("pending"))throw new IOException("Tally is still busy. Wait a moment and retry.");JSONObject result=value;
   main.post(()->{if(!active(epoch))return;cache.put(path,result);cacheAt.put(path,System.currentTimeMillis());render.accept(result);});
  }catch(Exception e){main.post(()->{if(!active(epoch))return;if(e instanceof Http.Failure&&(((Http.Failure)e).status==401||((Http.Failure)e).status==403)){showFailure(e);return;}List<Row> error=new ArrayList<>();error.add(heading("Could not load this report",e.getMessage()==null?"Connection unavailable":e.getMessage()));error.add(row("Retry","Pairing is kept","",()->{forceNext=true;self.run();}));rows(title,error,false);});}});
 }
 private String path(String endpoint,String...params){return BridgeApi.path(endpoint,company,params);}
 private void home(){load("Overview","/api/v1/mobile/bootstrap",this::home,b->{boot=b;selectInitialCompany();renderHome();});}
 private void renderHome(){List<Row> data=new ArrayList<>();JSONObject sm=object(object(boot,"summaries"),company),sync=object(boot,"autoSync");data.add(heading(company.isEmpty()?"Waiting for a Tally company":"Your business at a glance",sync.optBoolean("running")?"Updating safely in the background":sync.optString("lastError","Read-only • automatic sync")));
  data.add(row("Receivable",time(sm.optString("rFetchedAt")),amountOrMissing(sm,"receivable"),()->open(()->outstanding("receivable"))));data.add(row("We need to pay",time(sm.optString("pFetchedAt")),amountOrMissing(sm,"payable"),()->open(()->outstanding("payable"))));data.add(row("Sales this month",time(sm.optString("sFetchedAt")),amountOrMissing(sm,"sales"),()->open(()->register("sales"))));
  data.add(row("Universal search","Customers, ledgers, invoices and saved LR/RR numbers","",()->open(this::search)));data.add(row("Today's dispatch","Open invoice details and share","",()->open(this::dispatch)));data.add(row("Outstanding ageing","Age buckets with saved-data coverage","",()->open(this::ageing)));data.add(row("Favourite customers","Frequently used ledgers","",()->open(this::favourites)));rows("Overview",data,false);}
 private void ledgers(boolean groups){Runnable self=()->ledgers(groups);load(groups?"Ledger groups":"Ledgers",path("ledgers"),self,x->{List<Row> data=withSource(x);data.add(row(groups?"Show ledgers":"Show groups","Switch list","",()->ledgers(!groups)));JSONArray a=array(x,"ledgers");if(groups){TreeMap<String,Integer> counts=new TreeMap<>();for(int i=0;i<a.length();i++){JSONObject v=a.optJSONObject(i);if(v!=null&&!v.optString("parent").isEmpty())counts.merge(v.optString("parent"),1,Integer::sum);}for(Map.Entry<String,Integer> e:counts.entrySet()){String name=e.getKey();data.add(row(name,e.getValue()+" ledgers","",()->open(()->group(name))));}}else{for(int i=0;i<a.length();i++){JSONObject v=a.optJSONObject(i);if(v==null)continue;String name=v.optString("name");data.add(row(name,v.optString("parent"),"",()->open(()->ledger(name))));}}empty(data,a.length(),"No ledgers returned yet. Open the company in Tally and let the PC sync.");rows(groups?"Ledger groups":"Ledgers",data,true);});}
 private void ledger(String name){List<Row> data=new ArrayList<>();data.add(heading(name,"Choose a report"));data.add(row("Customer 360","Invoices, pending bills and payment activity","",()->open(()->customer(name))));data.add(row("Statement by date","Opening, debit, credit and closing balances","",()->open(()->dateMenu(name))));data.add(row("Outstanding balance","Pending bills and verified balance","",()->open(()->ledgerOutstanding(name))));data.add(row("Ledger details","Address, contact and tax information","",()->open(()->ledgerDetails(name))));boolean favorite=isFavourite(name);data.add(row(favorite?"Remove from favourites":"Add to favourites","Saved for this company on this phone","",()->{toggleFavourite(name);ledger(name);}));local("Customer",()->ledger(name),data,false);}
 private void dateMenu(String name){LocalDate now=LocalDate.now(),fy=LocalDate.of(now.getMonthValue()<4?now.getYear()-1:now.getYear(),4,1);List<Row> data=new ArrayList<>();String[] labels={"Today","This month","Last 30 days","Financial year"};LocalDate[] starts={now,now.withDayOfMonth(1),now.minusDays(29),fy};for(int i=0;i<labels.length;i++){LocalDate from=starts[i];data.add(row(labels[i],from+" to "+now,"",()->open(()->statement(name,from.toString(),now.toString()))));}data.add(row("Custom dates","Choose start and end dates","",()->pickRange(name)));local("Statement period",()->dateMenu(name),data,false);}
 private void pickRange(String name){LocalDate now=LocalDate.now();new DatePickerDialog(this,(v,y,m,d)->{LocalDate from=LocalDate.of(y,m+1,d);DatePickerDialog end=new DatePickerDialog(this,(v2,y2,m2,d2)->{LocalDate to=LocalDate.of(y2,m2+1,d2);if(to.isBefore(from)){toast("End date must be on or after start date");return;}open(()->statement(name,from.toString(),to.toString()));},now.getYear(),now.getMonthValue()-1,now.getDayOfMonth());end.setTitle("To date");end.show();},now.getYear(),now.getMonthValue()-1,now.getDayOfMonth()).show();}
 private void statement(String name,String from,String to){load("Ledger statement",path("ledger-statement","ledger",name,"from",from,"to",to),()->statement(name,from,to),x->{List<Row> data=withSource(x);data.add(heading(name,from+" to "+to));data.add(row("Opening balance",x.optString("balanceNote"),balance(x,"openingBalance"),null));data.add(row("Total debit / credit",money(x.optDouble("debitTotal"))+" Dr • "+money(x.optDouble("creditTotal"))+" Cr",balance(x,"closingBalance"),null));shareRows(data,x.optString("shareText"),path("ledger-statement-pdf","ledger",name,"from",from,"to",to),"Ledger-"+name);JSONArray vouchers=array(x,"vouchers");for(int i=0;i<vouchers.length();i++){JSONObject v=vouchers.optJSONObject(i);if(v==null)continue;String detail=v.optString("date")+" • "+v.optString("voucherType")+" • "+v.optString("party")+"\nDebit "+amountOrMissing(v,"debit")+" • Credit "+amountOrMissing(v,"credit");data.add(row(v.optString("number"),detail,"Balance "+balance(v,"balance"),v.optString("masterId").isEmpty()?null:()->open(()->invoice(v))));}empty(data,vouchers.length(),"No entries in this period.");rows("Ledger statement",data,true);});}
 private void ledgerOutstanding(String name){load("Outstanding balance",path("ledger-outstanding","ledger",name),()->ledgerOutstanding(name),x->{List<Row> data=withSource(x);data.add(row(name,x.optString("balanceFrom"),money(x.optDouble("total"))+" "+x.optString("drCr"),null));if(x.optBoolean("summaryOnly"))data.add(heading("Balance only","Tally did not return bill-wise detail. This is the verified saved ledger total."));shareRows(data,x.optString("shareText"),path("ledger-outstanding-pdf","ledger",name),"Outstanding-"+name);JSONArray bills=array(x,"bills");for(int i=0;i<bills.length();i++){JSONObject b=bills.optJSONObject(i);if(b==null)continue;data.add(row(b.optString("billNumber"),b.optString("date")+" • Due "+b.optString("dueDate")+" • "+b.optInt("ageing")+" days",money(b.optDouble("pendingAmount"))+" "+b.optString("drCr"),null));}rows("Outstanding balance",data,true);});}
 private void ledgerDetails(String name){load("Ledger details",path("ledger-details","ledger",name),()->ledgerDetails(name),x->{List<Row> data=withSource(x);JSONObject details=object(x,"details");Iterator<String> it=details.keys();while(it.hasNext()){String k=it.next();data.add(row(label(k),details.optString(k),"",null));}rows(name,data,false);});}
 private void outstanding(String type){load(type.equals("payable")?"We need to pay":"Receivable",path("outstanding","type",type),()->outstanding(type),x->{List<Row> data=withSource(x);data.add(row(type.equals("payable")?"Switch to receivable":"Switch to payable","","",()->outstanding(type.equals("payable")?"receivable":"payable")));data.add(row("Total "+type,x.optInt("count")+" parties",money(x.optDouble("total")),null));JSONArray a=array(x,"parties");for(int i=0;i<a.length();i++){JSONObject v=a.optJSONObject(i);if(v==null)continue;String name=v.optString("party");data.add(row(name,v.optString("parent"),money(v.optDouble("amount"))+" "+v.optString("drCr"),()->open(()->ledgerOutstanding(name))));}empty(data,a.length(),"No outstanding parties returned.");rows(type.equals("payable")?"We need to pay":"Receivable",data,true);});}
 private void group(String name){load("Group balances",path("group-balances","group",name),()->group(name),x->{List<Row> data=withSource(x);data.add(row(name,"Debit "+money(x.optDouble("drTotal"))+" • Credit "+money(x.optDouble("crTotal")),money(x.optDouble("total")),null));shareRows(data,x.optString("shareText"),path("group-balances-pdf","group",name),"Group-"+name);JSONArray a=array(x,"ledgers");for(int i=0;i<a.length();i++){JSONObject v=a.optJSONObject(i);if(v==null)continue;String ledger=v.optString("ledger");data.add(row(ledger,v.optString("parent"),money(v.optDouble("balance"))+" "+v.optString("drCr"),()->open(()->ledger(ledger))));}rows("Group balances",data,true);});}
 private void reports(){List<Row> data=new ArrayList<>();data.add(heading("Daily work","Registers and customer reports"));data.add(row("Today's dispatch","Invoices with dispatch details","",()->open(this::dispatch)));data.add(row("Outstanding ageing","Saved bill coverage shown","",()->open(this::ageing)));data.add(row("Universal search","Find an invoice or customer","",()->open(this::search)));data.add(row("Customer 360","Select a customer from Ledgers","",()->open(()->ledgers(false))));data.add(row("Sales register","Financial year → month → invoice","",()->open(()->register("sales"))));data.add(row("Purchase register","Financial year → month → voucher","",()->open(()->register("purchase"))));for(String name:new String[]{"Day Book","Trial Balance","Profit and Loss","Balance Sheet"})data.add(row(name,"Accounting report","",()->open(()->genericReport(name))));data.add(row("Bills receivable","Customer balances","",()->open(()->outstanding("receivable"))));data.add(row("Bills payable","Supplier balances","",()->open(()->outstanding("payable"))));local("Reports",this::reports,data,false);}
 private void register(String kind){String title=kind.equals("purchase")?"Purchase register":"Sales register";load(title,path("vouchers","type",kind,"period","fy","refresh","1"),()->register(kind),x->{List<Row> data=withSource(x);data.add(row("Financial-year total",x.optInt("count")+" vouchers",money(x.optDouble("total")),null));JSONArray a=array(x,"vouchers");TreeMap<String,JSONArray> months=new TreeMap<>(Collections.reverseOrder());LocalDate now=LocalDate.now();LocalDate fy=LocalDate.of(now.getMonthValue()<4?now.getYear()-1:now.getYear(),4,1);for(int i=0;i<12;i++)months.put(fy.plusMonths(i).toString().substring(0,7),new JSONArray());for(int i=0;i<a.length();i++){JSONObject v=a.optJSONObject(i);if(v==null)continue;String date=v.optString("date"),month=date.length()>=7?date.substring(0,7):"Unknown";if(!months.containsKey(month))months.put(month,new JSONArray());months.get(month).put(v);}data.add(row("All vouchers","Search the complete register","",()->open(()->vouchers(title,a,x))));for(Map.Entry<String,JSONArray> entry:months.entrySet()){String month=entry.getKey();JSONArray values=entry.getValue();double total=0;for(int i=0;i<values.length();i++)total+=Math.abs(values.optJSONObject(i).optDouble("amount"));data.add(row(monthLabel(month),values.length()+" vouchers",money(total),()->open(()->vouchers(monthLabel(month),values,x))));}rows(title,data,false);});}
 private void vouchers(String title,JSONArray vouchers,JSONObject source){List<Row> data=withSource(source);addVouchers(data,vouchers);empty(data,vouchers.length(),"No vouchers in this period.");local(title,()->vouchers(title,vouchers,source),data,true);}
 private void addVouchers(List<Row> data,JSONArray a){for(int i=0;i<a.length();i++){JSONObject v=a.optJSONObject(i);if(v==null)continue;data.add(row(v.optString("number","Voucher"),v.optString("party")+"\n"+v.optString("date")+" • "+v.optString("voucherType"),money(v.optDouble("amount")),()->open(()->invoice(v))));}}
 private void invoice(JSONObject hint){String id=hint.optString("masterId");if(id.isEmpty()){toast("Refresh this register to obtain the voucher identifier");goBack();return;}load("Invoice "+hint.optString("number"),path("voucher-detail","masterId",id,"number",hint.optString("number"),"date",hint.optString("date"),"party",hint.optString("party"),"amount",hint.optString("amount")),()->invoice(hint),x->{List<Row> data=withSource(x);data.add(heading(x.optString("firmName",company),x.optString("voucherType")));data.add(row(x.optString("customerName"),x.optString("customerCity")+"\n"+join(array(x,"customerAddress"))+"\n"+x.optString("gstin"),"",null));data.add(row("Invoice "+x.optString("invoiceNumber"),x.optString("invoiceDate"),money(x.optDouble("totalAmount")),null));for(String key:new String[]{"dispatchedThrough","lrNumber","lrDate","destination","vehicleNumber","eWayBillNumber"})if(!x.optString(key).isEmpty())data.add(row(label(key),x.optString(key),"",null));JSONArray items=array(x,"items");for(int i=0;i<items.length();i++){JSONObject it=items.optJSONObject(i);if(it==null)continue;data.add(row((i+1)+". "+it.optString("name"),"Quantity "+it.optString("quantity")+" • Rate "+it.optString("rate")+(it.optString("hsn").isEmpty()?"":" • HSN "+it.optString("hsn")),money(it.optDouble("amount")),null));}for(String key:new String[]{"discountAmount","taxableAmount","cgst","sgst","igst","freight","roundOff"})if(x.optDouble(key)!=0)data.add(row(label(key),"",money(x.optDouble(key)),null));data.add(row("Total amount","",money(x.optDouble("totalAmount")),null));if(!x.optString("narration").isEmpty())data.add(row("Narration",x.optString("narration"),"",null));String bank=object(boot,"pdfBanks").optString(company.trim().toLowerCase(Locale.ROOT));data.add(heading("PDF bank",bank.isEmpty()?"No bank details selected. Set the default once on the PC.":bank+" • saved on the PC"));shareRows(data,x.optString("shareText"),path("voucher-pdf","masterId",id),"Invoice-"+x.optString("invoiceNumber"));rows("Invoice "+x.optString("invoiceNumber"),data,false);});}
 private void genericReport(String name){load(name,path("report","name",name),()->genericReport(name),x->{List<Row> data=withSource(x);JSONArray a=array(x,"rows");for(int i=0;i<a.length();i++){JSONObject v=a.optJSONObject(i);if(v==null)continue;StringBuilder detail=new StringBuilder();Iterator<String> keys=v.keys();while(keys.hasNext()){String k=keys.next();detail.append(label(k)).append(": ").append(v.optString(k)).append('\n');}data.add(row("Entry "+(i+1),detail.toString().trim(),"",null));}empty(data,a.length(),"Tally returned no normalized rows for this report.");rows(name,data,true);});}
 private void search(){load("Universal search",path("search-index"),this::search,x->{List<Row> data=withSource(x);data.add(heading("Search saved information","Invoice and LR/RR search covers the data already synced or opened."));JSONArray a=array(x,"results");for(int i=0;i<a.length();i++){JSONObject v=a.optJSONObject(i);if(v==null)continue;String ledger=v.optString("ledger",v.optString("party",v.optString("title")));data.add(row(v.optString("title"),v.optString("subtitle")+" "+v.optString("number")+" "+v.optString("lrNumber"),v.has("amount")?money(v.optDouble("amount")):"",()->open(v.optString("masterId").isEmpty()?()->ledger(ledger):()->invoice(v))));}empty(data,a.length(),"No saved search results yet.");rows("Universal search",data,true);});}
 private void dispatch(){load("Today's dispatch",path("today-dispatch"),this::dispatch,x->{List<Row> data=withSource(x);data.add(row("Today's total",x.optInt("count")+" vouchers",money(x.optDouble("total")),null));JSONArray a=array(x,"vouchers");addVouchers(data,a);empty(data,a.length(),"No dispatch vouchers returned for today.");rows("Today's dispatch",data,true);});}
 private void ageing(){load("Outstanding ageing",path("ageing"),this::ageing,x->{List<Row> data=withSource(x);data.add(heading("Saved bill coverage",x.optInt("coveredParties")+" of "+x.optInt("totalParties")+" parties • "+x.optInt("coveragePercent")+"%\nOpen a customer's outstanding report to add bill details. Partial coverage is not the complete receivable total."));data.add(row("Covered outstanding",x.optInt("billCount")+" bills",money(x.optDouble("total")),null));JSONArray a=array(x,"buckets");for(int i=0;i<a.length();i++){JSONObject b=a.optJSONObject(i);if(b!=null)data.add(row(b.optString("label"),b.optInt("bills")+" bills",money(b.optDouble("amount")),null));}rows("Outstanding ageing",data,false);});}
 private void customer(String name){load("Customer 360",path("customer360","ledger",name),()->customer(name),x->{List<Row> data=withSource(x);data.add(row(name,x.optInt("pendingBillCount")+" pending bills",money(x.optDouble("outstanding")),null));data.add(row("Overdue","Saved bill details",money(x.optDouble("overdue")),null));data.add(row("Open outstanding","Refresh bill-wise information","",()->open(()->ledgerOutstanding(name))));data.add(row("Date statement","View activity for a selected period","",()->open(()->dateMenu(name))));JSONObject payment=x.optJSONObject("lastPayment");if(payment!=null)data.add(row("Last payment",payment.optString("date")+" • "+payment.optString("number"),money(payment.optDouble("amount")),()->open(()->invoice(payment))));shareRows(data,x.optString("shareText"),path("customer360-pdf","ledger",name),"Customer-"+name);data.add(heading("Latest invoices",""));addVouchers(data,array(x,"latestInvoices"));data.add(heading("Recent activity",""));addVouchers(data,array(x,"recentActivity"));rows("Customer 360",data,false);});}
 private void more(){List<Row> data=new ArrayList<>();data.add(heading("Connection",store.get("base")+"\nAllowed account: "+store.get("email")));data.add(row("Last successful Tally read",time(boot.optString("lastSuccess")),"",null));data.add(row("Sync now","Request a safe sequential background update","",this::syncNow));data.add(row("Test Tally connection","Check the PC can read the open company","",this::probe));data.add(row("Universal search","Search saved data","",()->open(this::search)));data.add(row("Favourite customers","Saved on this phone","",()->open(this::favourites)));data.add(row("Default PDF bank",object(boot,"pdfBanks").optString(company.trim().toLowerCase(Locale.ROOT),"Not selected")+"\nChange in Windows setup → PDF Bank","",null));data.add(row("Lock app","Use fingerprint or phone screen lock to reopen","",()->{unlocked=false;showLock();}));data.add(row("Renew Google sign-in","Keeps your approved phone key","",this::connectScreen));data.add(row("Reset phone pairing","Requires new desktop approval","",this::reset));data.add(heading("TallyBridge 2.0 native preview","Read-only • no WebView • Android Keystore\nPDFs and exported details remain in the apps you share to."));local("More",this::more,data,false);}
 private void syncNow(){int epoch=generation;progress.setVisibility(View.VISIBLE);String selected=company;work.execute(()->{try{JSONObject result=api.call("/api/v1/mobile/sync","POST",new JSONObject().put("company",selected).put("reason","android").toString());main.post(()->{if(active(epoch)){progress.setVisibility(View.GONE);toast(result.optBoolean("started")?"Sync started safely":"Sync is already running");}});}catch(Exception e){main.post(()->{if(active(epoch)){progress.setVisibility(View.GONE);toast(e.getMessage());}});}});}
 private void probe(){int epoch=generation;progress.setVisibility(View.VISIBLE);work.execute(()->{try{api.call("/api/v1/mobile/probe","POST","{}");main.post(()->{if(active(epoch)){progress.setVisibility(View.GONE);toast("Tally connection confirmed");}});}catch(Exception e){main.post(()->{if(active(epoch)){progress.setVisibility(View.GONE);toast(e.getMessage());}});}});}
 private String favouritesKey(){return "favourites:"+company;}
 private JSONArray favouriteArray(){try{return new JSONArray(store.get(favouritesKey()));}catch(Exception e){return new JSONArray();}}
 private boolean isFavourite(String name){JSONArray a=favouriteArray();for(int i=0;i<a.length();i++)if(name.equals(a.optString(i)))return true;return false;}
 private void toggleFavourite(String name){JSONArray a=favouriteArray(),out=new JSONArray();boolean found=false;for(int i=0;i<a.length();i++){String v=a.optString(i);if(name.equals(v))found=true;else out.put(v);}if(!found)out.put(name);store.put(favouritesKey(),out.toString());}
 private void favourites(){List<Row> data=new ArrayList<>();JSONArray a=favouriteArray();for(int i=0;i<a.length();i++){String name=a.optString(i);data.add(row(name,"Open customer","",()->open(()->ledger(name))));}empty(data,a.length(),"Open a ledger and choose Add to favourites.");local("Favourite customers",this::favourites,data,true);}
 private void shareRows(List<Row> data,String text,String pdfPath,String name){if(!text.isEmpty())data.add(row("Share details only","Choose WhatsApp or another app","",()->shareText(text)));data.add(row("Preview PDF","Native viewer with page navigation and zoom","",()->fetchPDF(pdfPath,name,text,0)));data.add(row("Share PDF","Includes the default bank saved on your PC","",()->fetchPDF(pdfPath,name,"",1)));if(!text.isEmpty())data.add(row("Share PDF + details","Attach the PDF with its message","",()->fetchPDF(pdfPath,name,text,1)));data.add(row("Save PDF","Choose a folder on your phone","",()->fetchPDF(pdfPath,name,"",2)));}
 private void shareText(String text){try{Intent i=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,text);startActivity(Intent.createChooser(i,"Share details"));}catch(Exception e){toast("No sharing app available");}}
 private void fetchPDF(String path,String name,String message,int mode){if(pdfBusy){toast("A PDF is already being prepared");return;}pdfBusy=true;int epoch=generation;progress.setVisibility(View.VISIBLE);work.execute(()->{try{if(generation!=epoch){main.post(()->pdfBusy=false);return;}byte[] b=api.pdf(path);String safe=name.replaceAll("[^\\p{L}\\p{N}._-]","-");if(safe.length()>90)safe=safe.substring(0,90);File dir=new File(getCacheDir(),"pdf");if(!dir.exists()&&!dir.mkdirs())throw new IOException("Could not prepare PDF storage");File f=new File(dir,safe+"-"+UUID.randomUUID().toString().substring(0,8)+".pdf");try(FileOutputStream out=new FileOutputStream(f)){out.write(b);}main.post(()->{pdfBusy=false;if(!active(epoch)){f.delete();return;}progress.setVisibility(View.GONE);if(mode==0)open(()->previewPDF(f,message,0));else if(mode==1)sharePDF(f,message);else savePDF(f);});}catch(Exception e){main.post(()->{pdfBusy=false;if(active(epoch)){progress.setVisibility(View.GONE);toast(e.getMessage());}});}});}
 private void sharePDF(File file,String message){Uri uri=Uri.parse("content://in.tallybridge.app.pdf/"+Uri.encode(file.getName()));Intent i=new Intent(Intent.ACTION_SEND).setType("application/pdf").putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);i.setClipData(ClipData.newRawUri("Invoice PDF",uri));if(!message.isEmpty())i.putExtra(Intent.EXTRA_TEXT,message);try{startActivity(Intent.createChooser(i,"Share PDF"));}catch(Exception e){toast("No PDF sharing app available");}}
 private void savePDF(File file){savePDF=file;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("application/pdf").putExtra(Intent.EXTRA_TITLE,file.getName());try{startActivityForResult(i,702);}catch(Exception e){toast("No file picker available");}}
 private void previewPDF(File file,String message,int page){current=()->previewPDF(file,message,page);int epoch=++generation;base("PDF preview",true);progress.setVisibility(View.VISIBLE);work.execute(()->{try(ParcelFileDescriptor descriptor=ParcelFileDescriptor.open(file,ParcelFileDescriptor.MODE_READ_ONLY);PdfRenderer renderer=new PdfRenderer(descriptor)){int count=renderer.getPageCount();int index=Math.max(0,Math.min(page,count-1));Bitmap bitmap;try(PdfRenderer.Page p=renderer.openPage(index)){float scale=Math.min(2f,1800f/Math.max(p.getWidth(),p.getHeight()));bitmap=Bitmap.createBitmap(Math.max(1,Math.round(p.getWidth()*scale)),Math.max(1,Math.round(p.getHeight()*scale)),Bitmap.Config.ARGB_8888);bitmap.eraseColor(Color.WHITE);p.render(bitmap,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);}main.post(()->{if(!active(epoch)){bitmap.recycle();return;}progress.setVisibility(View.GONE);LinearLayout controls=new LinearLayout(this);Button previous=button("Previous",()->previewPDF(file,message,index-1)),next=button("Next",()->previewPDF(file,message,index+1));previous.setEnabled(index>0);next.setEnabled(index+1<count);controls.addView(previous,new LinearLayout.LayoutParams(0,-2,1));controls.addView(text((index+1)+" / "+count,15,NAVY));controls.addView(next,new LinearLayout.LayoutParams(0,-2,1));body.addView(controls);PdfPageView view=new PdfPageView(this,bitmap);body.addView(view,new LinearLayout.LayoutParams(-1,0,1));body.addView(button("Share PDF",()->sharePDF(file,message)));body.addView(button("Save PDF",()->savePDF(file)));});}catch(Exception e){main.post(()->{if(active(epoch)){progress.setVisibility(View.GONE);toast("Could not preview PDF: "+e.getMessage());}});}});}
 private void cleanPDFs(){File dir=new File(getCacheDir(),"pdf");File[] files=dir.listFiles();if(files!=null)for(File file:files)if(System.currentTimeMillis()-file.lastModified()>24*60*60*1000L)file.delete();}
 private List<Row> withSource(JSONObject x){List<Row> data=new ArrayList<>();String fetched=x.optString("fetchedAt");data.add(heading(x.optBoolean("live")?"Live from Tally":"Last updated data",time(fetched)+(x.optString("liveError").isEmpty()?"":"\n"+x.optString("liveError"))));return data;}
 private void empty(List<Row> data,int count,String message){if(count==0)data.add(heading("Nothing to show",message));}
 private String amountOrMissing(JSONObject x,String key){return !x.has(key)||x.isNull(key)?"Not updated":money(x.optDouble(key));}
 private String money(double amount){return currency.format(amount);}
 private String balance(JSONObject x,String key){if(!x.has(key)||x.isNull(key))return "Unavailable";double n=x.optDouble(key);return money(Math.abs(n))+(n<0?" Dr":n>0?" Cr":"");}
 private String time(String value){if(value.isEmpty()||value.startsWith("0001"))return "Not updated yet";try{return "Updated "+Instant.parse(value).atZone(ZoneId.systemDefault()).format(DateTimeFormatter.ofPattern("dd MMM yyyy, h:mm a"));}catch(Exception e){return value;}}
 private String monthLabel(String value){try{return YearMonth.parse(value).format(DateTimeFormatter.ofPattern("MMMM yyyy"));}catch(Exception e){return value;}}
 private static JSONObject object(JSONObject o,String key){JSONObject x=o.optJSONObject(key);return x==null?new JSONObject():x;}
 private static JSONArray array(JSONObject o,String key){JSONArray x=o.optJSONArray(key);return x==null?new JSONArray():x;}
 private String join(JSONArray a){StringBuilder b=new StringBuilder();for(int i=0;i<a.length();i++){if(i>0)b.append(", ");b.append(a.optString(i));}return b.toString();}
 private String label(String key){Map<String,String> labels=Http.pairs("lrNumber","LR/RR number","lrDate","Dispatch date","dispatchedThrough","Dispatched through","eWayBillNumber","E-way bill","gstin","GSTIN","NAME","Name","PARENT","Group","PARTYGSTIN","GSTIN","INCOMETAXNUMBER","PAN","LEDGERPHONE","Phone","EMAIL","Email","STATENAME","State","PINCODE","Pincode","CLOSINGBALANCE","Closing balance","BANKNAME","Bank","BANKACCOUNTNUMBER","Account number","BANKACCHOLDERNAME","Account holder","IFSCCODE","IFSC","BRANCHNAME","Branch","UPIID","UPI","ADDRESS","Address","cgst","CGST","sgst","SGST","igst","IGST");return labels.containsKey(key)?labels.get(key):key.replaceAll("([a-z])([A-Z])","$1 $2");}
 private void toast(String message){if(!destroyed)Toast.makeText(this,message==null?"Please retry":message,Toast.LENGTH_LONG).show();}
}
